# Site settings
title: CS231n Convolutional Neural Networks for Visual Recognition
email: team.aikorea@gmail.com
description: "스탠포드 CS231n: Convolutional Neural Networks for Visual Recognition 수업자료 번역사이트"
baseurl: "/cs231n"
url: "http://aikorea.org"
twitter_username: kjw6612
github_username:  aikorea

# Build settings
markdown: redcarpet
permalink: pretty
